# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true
    resource_class: medium
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx6400m
      GRAALVM_HOME: /home/circleci/repo/.graalvm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build All Variants
          command: ./mvnw clean install -Pjpa -Pinfinispan -Pkafka -Pstreams -DskipTests
      - run:
          name: Verify (Standard)
          command: ./mvnw -Pjpa test
      - run:
          name: Run QE Tests
          command: ./mvnw verify -Pall -pl tests -Dmaven.javadoc.skip=true
      # - run:
      #     name: Install GraalVM
      #     command: curl https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-linux-amd64-19.1.1.tar.gz -O -J -L && tar xfz graalvm-ce-linux-amd64-19.1.1.tar.gz && mv graalvm-ce-19.1.1 .graalvm && rm graalvm-ce-linux-amd64-19.1.1.tar.gz
      # - run: 
      #     name: Install native-image
      #     command: $GRAALVM_HOME/bin/gu install native-image
      # - run:
      #     name: Build & Verify (Native)
      #     command: ./mvnw clean package verify -Pnative
      #     no_output_timeout: 40m
