site:
  title: Apicurio Registry
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://www.apicur.io/registry/docs
  start_page: apicurio-registry::index.adoc
content:
  sources:
  - url: ..
    branches: HEAD
    start_path: .antora
    edit_url: '{web_url}'

ui:
  bundle:
    url: https://raw.githubusercontent.com/Apicurio/apicurio-docs-ui/master/dist/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  output_dir: assets

output:
  dir: ./dist

asciidoc:
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
    mod-loc: partial$
    registry: Apicurio Registry
    apicurio-registry: true
