apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-tracing-demo

resources:
  - namespace.yaml
  - jaeger.yaml
  - otel-collector.yaml
  - kafka.yaml
  - registry.yaml
  - producer.yaml
  - consumer.yaml

commonLabels:
  app.kubernetes.io/part-of: otel-tracing-demo
  app.kubernetes.io/managed-by: kustomize
